#!/usr/bin/env python3
"""Plot Figure 2 as Case C minus Case B shortcut-specification sensitivity.

The script reads the full-precision per-N CSV exports used for the commercial
3-SAT and open-weight 2-SAT analyses.  It aligns rows by the complete frozen
model/configuration identifier and N, verifies that prediction-derived fields
are unchanged, and plots only quantities affected by complexity
residualization:

  * charged shortcut ceiling;
  * normalized point margin;
  * normalized Clopper--Pearson margin;
  * normalized Wilson margin.

Figure 1 is intentionally generated by a different script and is not touched.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
from matplotlib.lines import Line2D


SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
THREE_SAT_CASE_B = REPO_ROOT / (
    "SAT_Group_Evaluation/analysis/commercial_api_results_analysis/"
    "rmc_filtered_RMC_caseB_by_N.csv"
)
THREE_SAT_CASE_C = REPO_ROOT / (
    "SAT_Group_Evaluation/analysis/commercial_api_results_analysis/"
    "rmc_filtered_caseC_delta_estimated_by_N.csv"
)
TWO_SAT_CASE_B = REPO_ROOT / (
    "SAT_Group_Evaluation/analysis/open_source_LLM_2SAT_analysis/"
    "rmc_paper_open_vendor_case_b_by_N.csv"
)
TWO_SAT_CASE_C = REPO_ROOT / (
    "SAT_Group_Evaluation/analysis/open_source_LLM_2SAT_analysis/"
    "rmc_paper_open_vendor_case_c_by_N.csv"
)

DEFAULT_OUTPUT_DIR = SCRIPT_DIR / "figures" / "shortcut_margin"


@dataclass(frozen=True)
class DomainSpec:
    domain: str
    case_b_path: Path
    case_c_path: Path
    model_order: tuple[str, ...]
    model_labels: dict[str, str]
    excluded_n: frozenset[int]
    ceiling_column: str
    point_column: str
    cp_column: str
    wilson_column: str
    signed_cp_column: str
    unchanged_columns: tuple[str, ...]
    output_pdf: str
    output_png: str
    show_legend: bool


THREE_SAT_MODELS = {
    "gpt-5": "GPT-5",
    "claude_batch_groups_zero_shot_desc_adaptive_thinking_medium_effort": (
        "Opus 4.7\n(med. think)"
    ),
    "deepseek-reasoner": "DeepSeek-Reasoner",
}

TWO_SAT_MODELS = {
    (
        "Qwen3-14B__cnf_qwen3_14b_cases_prompt_interleave_zero_shot_desc_"
        "allN_3_5_8_10_15_20_25_30_40_50_60_thinking"
    ): "Qwen3-14B",
    (
        "Qwen3-32B__cnf_qwen3_32b_cases_prompt_interleave_zero_shot_desc_"
        "allN_3_5_8_10_15_20_25_30_40_50_60_thinking"
    ): "Qwen3-32B",
    (
        "QwQ-32B__cnf_qwq_32b_cases_prompt_interleave_zero_shot_desc_"
        "allN_3_5_8_10_15_20_25_30_40_50_60_thinking"
    ): "QwQ-32B",
    (
        "gpt-oss-20b__cnf_gpt_oss_20b_cases_prompt_interleave_zero_shot_desc_"
        "allN_3_5_8_10_15_20_25_30_40_50_60_thinking"
    ): "gpt-oss-20b",
    (
        "Nemotron-H-47B-Reasoning-128K__cnf_nemotron_h_47b_reasoning_128k_"
        "cases_prompt_interleave_zero_shot_desc_allN_3_5_8_10_15_20_25_30_"
        "40_50_60_thinking_reasoning_on"
    ): "Nemotron-H-47B",
    (
        "Llama-3_3-Nemotron-Super-49B-v1_5__cnf_llama_nemotron_super_49b_v15_"
        "cases_prompt_interleave_zero_shot_desc_allN_3_5_8_10_15_20_25_30_"
        "40_50_60_thinking_reasoning_on"
    ): "Llama-Nemotron-49B",
}


DOMAIN_SPECS = (
    DomainSpec(
        domain="3-SAT",
        case_b_path=THREE_SAT_CASE_B,
        case_c_path=THREE_SAT_CASE_C,
        model_order=tuple(THREE_SAT_MODELS),
        model_labels=THREE_SAT_MODELS,
        excluded_n=frozenset(),
        ceiling_column="null_ceil",
        point_column="global_pooled_nRMC_without_LCB",
        cp_column="global_pooled_nRMC",
        wilson_column="wilson_pooled_nRMC",
        signed_cp_column="global_pooled_RMC_signed",
        unchanged_columns=(
            "Accuracy",
            "F1_SAT",
            "F1_UNSAT",
            "ADR",
            "ADR_with_assign",
            "global_pooled_separability_hat",
        ),
        output_pdf="fig_3sat_casec_byN.pdf",
        output_png="fig_3sat_casec_byN.png",
        show_legend=False,
    ),
    DomainSpec(
        domain="2-SAT",
        case_b_path=TWO_SAT_CASE_B,
        case_c_path=TWO_SAT_CASE_C,
        model_order=tuple(TWO_SAT_MODELS),
        model_labels=TWO_SAT_MODELS,
        # Figure 1 omits N=20, so Figure 2 uses the identical plotted N grid.
        excluded_n=frozenset({20}),
        ceiling_column="null_ceil",
        point_column="global_pooled_nRMC_without_LCB",
        cp_column="global_pooled_nRMC",
        wilson_column="wilson_pooled_nRMC",
        signed_cp_column="global_pooled_RMC_signed",
        unchanged_columns=(
            "Accuracy",
            "F1_SAT",
            "F1_UNSAT",
            "ADR",
            "ADR_with_assign",
            "global_pooled_separability_hat",
        ),
        output_pdf="fig_2sat_casec_byN.pdf",
        output_png="fig_2sat_casec_byN.png",
        show_legend=True,
    ),
)


MARGIN_STYLES = {
    "point": {
        "color": "#7B6AA8",
        "linestyle": "-",
        "marker": "o",
        "label": r"$\Delta$ normalized point margin",
    },
    "cp": {
        "color": "#B44E4D",
        "linestyle": "-",
        "marker": "s",
        "label": r"$\Delta$ normalized CP margin",
    },
    "wilson": {
        "color": "#8A6253",
        "linestyle": "--",
        "marker": "^",
        "label": r"$\Delta$ normalized Wilson margin",
    },
}

CEILING_STYLE = {
    "color": "#5F6B73",
    "linestyle": "-",
    "marker": "D",
}


def apply_academic_style() -> None:
    """Apply the bundled figure-polish style contract compatibly.

    The local Matplotlib release treats unescaped hexadecimal values in an
    mplstyle file as comments, so the equivalent restrained settings are
    applied through rcParams instead of loading that file directly.
    """
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
            "savefig.edgecolor": "white",
            "savefig.bbox": "tight",
            "savefig.pad_inches": 0.04,
            "savefig.dpi": 220,
            "axes.edgecolor": "#D8D1C7",
            "axes.labelcolor": "#4B5563",
            "axes.linewidth": 0.8,
            "axes.grid": True,
            "axes.axisbelow": True,
            "axes.spines.top": False,
            "axes.spines.right": False,
            "axes.titlesize": 11,
            "axes.labelsize": 10.5,
            "grid.color": "#E7E5E4",
            "grid.linewidth": 0.65,
            "grid.alpha": 0.65,
            "font.size": 10,
            "font.family": "sans-serif",
            "xtick.color": "#6B7280",
            "ytick.color": "#6B7280",
            "xtick.labelsize": 9,
            "ytick.labelsize": 9,
            "legend.frameon": False,
            "legend.fontsize": 9,
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
        }
    )


def read_selected_rows(path: Path, spec: DomainSpec) -> tuple[dict, list[str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {path}")
        fieldnames = reader.fieldnames
        rows = list(reader)

    required = {
        "model",
        "N",
        spec.ceiling_column,
        spec.point_column,
        spec.cp_column,
        spec.wilson_column,
        spec.signed_cp_column,
        *spec.unchanged_columns,
    }
    missing_columns = sorted(required - set(fieldnames))
    if missing_columns:
        raise ValueError(f"Missing columns in {path}: {missing_columns}")

    selected: dict[tuple[str, int], dict[str, str]] = {}
    duplicate_keys: list[str] = []
    for row in rows:
        model = row["model"]
        if model not in spec.model_labels:
            continue
        n_value = int(row["N"])
        key = (model, n_value)
        if key in selected:
            duplicate_keys.append(f"{model}|N={n_value}")
        selected[key] = row

    if duplicate_keys:
        raise ValueError(f"Duplicate alignment keys in {path}: {duplicate_keys}")
    return selected, fieldnames


def parse_required_float(row: dict[str, str], column: str, key: tuple[str, int]) -> float:
    value = row.get(column, "")
    if value is None or value.strip() == "":
        raise ValueError(f"Missing required value {column} for {key}")
    return float(value)


def display_boundary(value: int | None) -> str:
    return r"$\varnothing$" if value is None else str(value)


def align_domain(spec: DomainSpec) -> tuple[dict[str, dict], dict]:
    case_b, _ = read_selected_rows(spec.case_b_path, spec)
    case_c, _ = read_selected_rows(spec.case_c_path, spec)

    keys_b = set(case_b)
    keys_c = set(case_c)
    unmatched_b = sorted(keys_b - keys_c)
    unmatched_c = sorted(keys_c - keys_b)
    common_keys = keys_b & keys_c

    missing_unchanged: list[dict] = []
    changed_prediction_fields: list[dict] = []
    aligned: dict[str, dict] = {}

    for model in spec.model_order:
        model_keys = sorted(key for key in common_keys if key[0] == model)
        all_signed_cp_original: list[tuple[int, float]] = []
        all_signed_cp_residualized: list[tuple[int, float]] = []
        series = {
            "N": [],
            "delta_ceiling": [],
            "delta_point": [],
            "delta_cp": [],
            "delta_wilson": [],
            "signed_cp_original": [],
            "signed_cp_residualized": [],
        }

        for key in model_keys:
            row_b = case_b[key]
            row_c = case_c[key]
            for column in spec.unchanged_columns:
                value_b = row_b.get(column, "")
                value_c = row_c.get(column, "")
                if not value_b or not value_c:
                    missing_unchanged.append(
                        {
                            "model_config": model,
                            "N": key[1],
                            "column": column,
                            "original": value_b,
                            "residualized": value_c,
                        }
                    )
                    continue
                numeric_b = float(value_b)
                numeric_c = float(value_c)
                if not math.isclose(
                    numeric_b, numeric_c, rel_tol=1e-12, abs_tol=1e-12
                ):
                    changed_prediction_fields.append(
                        {
                            "model_config": model,
                            "N": key[1],
                            "column": column,
                            "original": numeric_b,
                            "residualized": numeric_c,
                        }
                    )

            original_ceiling = parse_required_float(
                row_b, spec.ceiling_column, key
            )
            residual_ceiling = parse_required_float(
                row_c, spec.ceiling_column, key
            )
            original_point = parse_required_float(row_b, spec.point_column, key)
            residual_point = parse_required_float(row_c, spec.point_column, key)
            original_cp = parse_required_float(row_b, spec.cp_column, key)
            residual_cp = parse_required_float(row_c, spec.cp_column, key)
            original_wilson = parse_required_float(row_b, spec.wilson_column, key)
            residual_wilson = parse_required_float(row_c, spec.wilson_column, key)
            signed_cp_original = parse_required_float(
                row_b, spec.signed_cp_column, key
            )
            signed_cp_residualized = parse_required_float(
                row_c, spec.signed_cp_column, key
            )
            all_signed_cp_original.append((key[1], signed_cp_original))
            all_signed_cp_residualized.append((key[1], signed_cp_residualized))

            if key[1] in spec.excluded_n:
                continue

            series["N"].append(key[1])
            series["delta_ceiling"].append(residual_ceiling - original_ceiling)
            series["delta_point"].append(residual_point - original_point)
            series["delta_cp"].append(residual_cp - original_cp)
            series["delta_wilson"].append(residual_wilson - original_wilson)
            series["signed_cp_original"].append(signed_cp_original)
            series["signed_cp_residualized"].append(signed_cp_residualized)

        original_boundary = max(
            (
                n for n, signed in all_signed_cp_original
                if signed > 0
            ),
            default=None,
        )
        residual_boundary = max(
            (
                n for n, signed in all_signed_cp_residualized
                if signed > 0
            ),
            default=None,
        )
        series["boundary_original"] = original_boundary
        series["boundary_residualized"] = residual_boundary
        aligned[model] = series

    if changed_prediction_fields:
        raise ValueError(
            "Prediction-derived fields changed between specifications: "
            f"{changed_prediction_fields}"
        )

    report = {
        "domain": spec.domain,
        "source_original": str(spec.case_b_path),
        "source_residualized": str(spec.case_c_path),
        "alignment_key": ["domain", "model/configuration", "N"],
        "excluded_N_to_match_figure_1": sorted(spec.excluded_n),
        "matched_source_rows": len(common_keys),
        "plotted_rows": sum(len(series["N"]) for series in aligned.values()),
        "unmatched_original_rows": [f"{model}|N={n}" for model, n in unmatched_b],
        "unmatched_residualized_rows": [
            f"{model}|N={n}" for model, n in unmatched_c
        ],
        "missing_unchanged_fields": missing_unchanged,
        "changed_prediction_fields": changed_prediction_fields,
        "models": {},
    }

    for model in spec.model_order:
        series = aligned[model]
        report["models"][spec.model_labels[model].replace("\n", " ")] = {
            "model_config": model,
            "N": series["N"],
            "delta_ranges": {
                "shortcut_ceiling": [
                    min(series["delta_ceiling"]),
                    max(series["delta_ceiling"]),
                ],
                "normalized_point_margin": [
                    min(series["delta_point"]),
                    max(series["delta_point"]),
                ],
                "normalized_cp_margin": [
                    min(series["delta_cp"]),
                    max(series["delta_cp"]),
                ],
                "normalized_wilson_margin": [
                    min(series["delta_wilson"]),
                    max(series["delta_wilson"]),
                ],
            },
            "positive_cp_boundary_original": series["boundary_original"],
            "positive_cp_boundary_residualized": series[
                "boundary_residualized"
            ],
        }
    return aligned, report


def symmetric_limit(values: Iterable[float], minimum: float = 0.05) -> float:
    max_abs = max((abs(value) for value in values), default=minimum)
    padded = max(minimum, max_abs * 1.10)
    return math.ceil(padded / 0.02) * 0.02


def plot_domain(
    spec: DomainSpec,
    aligned: dict[str, dict],
    output_dir: Path,
    ceiling_limit: float,
    margin_limit: float,
) -> None:
    model_count = len(spec.model_order)
    figure_width = 12.2 if model_count == 3 else 15.0
    figure_height = 5.15 if not spec.show_legend else 5.75
    fig, axes = plt.subplots(
        2,
        model_count,
        figsize=(figure_width, figure_height),
        sharey="row",
        squeeze=False,
    )

    for column_index, model in enumerate(spec.model_order):
        label = spec.model_labels[model]
        series = aligned[model]
        n_values = series["N"]
        ax_ceiling = axes[0, column_index]
        ax_margin = axes[1, column_index]

        ax_ceiling.plot(
            n_values,
            series["delta_ceiling"],
            linewidth=2.0,
            markersize=5.0,
            **CEILING_STYLE,
        )
        ax_ceiling.axhline(0, color="#2F3437", linewidth=1.0, linestyle=":")
        ax_ceiling.set_ylim(-ceiling_limit, ceiling_limit)
        ax_ceiling.set_title(label, loc="center", fontsize=10 if model_count > 3 else 11)
        ax_ceiling.tick_params(axis="x", labelbottom=False)

        for metric in ("point", "cp", "wilson"):
            style = MARGIN_STYLES[metric]
            ax_margin.plot(
                n_values,
                series[f"delta_{metric}"],
                color=style["color"],
                linestyle=style["linestyle"],
                marker=style["marker"],
                linewidth=1.9,
                markersize=4.5,
            )
        ax_margin.axhline(0, color="#2F3437", linewidth=1.0, linestyle=":")
        ax_margin.set_ylim(-margin_limit, margin_limit)

        original_boundary = series["boundary_original"]
        residual_boundary = series["boundary_residualized"]
        if original_boundary != residual_boundary:
            ax_margin.set_title(
                rf"CP $N^*$: {display_boundary(original_boundary)}"
                rf"$\rightarrow${display_boundary(residual_boundary)}",
                loc="center",
                fontsize=8.5,
                pad=3,
                color="#374151",
            )

        tick_values = [
            n
            for n in ([5, 10, 25, 40, 60] if spec.domain == "3-SAT" else [3, 10, 25, 40, 60])
            if n in n_values
        ]
        ax_ceiling.set_xticks(tick_values)
        ax_margin.set_xticks(tick_values)
        ax_margin.set_xlabel(r"$N$")
        ax_ceiling.grid(True, axis="y")
        ax_margin.grid(True, axis="y")

    axes[0, 0].set_ylabel(
        r"$\Delta C_{\mathrm{sc}}$" + "\n(residualized $-$ original)"
    )
    axes[1, 0].set_ylabel(
        r"$\Delta$ normalized margin" + "\n(residualized $-$ original)"
    )

    if spec.show_legend:
        handles = [
            Line2D(
                [0],
                [0],
                color=MARGIN_STYLES[metric]["color"],
                linestyle=MARGIN_STYLES[metric]["linestyle"],
                marker=MARGIN_STYLES[metric]["marker"],
                linewidth=1.9,
                markersize=4.5,
                label=MARGIN_STYLES[metric]["label"],
            )
            for metric in ("point", "cp", "wilson")
        ]
        fig.legend(
            handles=handles,
            loc="lower center",
            bbox_to_anchor=(0.5, 0.005),
            ncol=3,
            frameon=False,
        )
        bottom = 0.15
    else:
        bottom = 0.04

    fig.tight_layout(rect=[0.01, bottom, 1.0, 0.99], h_pad=1.0, w_pad=0.8)
    output_dir.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_dir / spec.output_pdf)
    fig.savefig(output_dir / spec.output_png, dpi=220)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate Figure 2 complexity-residualization delta plots."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for PDF/PNG outputs and the alignment report.",
    )
    args = parser.parse_args()

    apply_academic_style()

    aligned_by_domain: dict[str, dict] = {}
    reports: list[dict] = []
    all_ceiling_deltas: list[float] = []
    all_margin_deltas: list[float] = []

    for spec in DOMAIN_SPECS:
        aligned, report = align_domain(spec)
        aligned_by_domain[spec.domain] = aligned
        reports.append(report)
        for series in aligned.values():
            all_ceiling_deltas.extend(series["delta_ceiling"])
            for metric in ("point", "cp", "wilson"):
                all_margin_deltas.extend(series[f"delta_{metric}"])

    ceiling_limit = symmetric_limit(all_ceiling_deltas)
    margin_limit = symmetric_limit(all_margin_deltas)

    for spec in DOMAIN_SPECS:
        plot_domain(
            spec,
            aligned_by_domain[spec.domain],
            args.output_dir,
            ceiling_limit,
            margin_limit,
        )

    audit = {
        "comparison": "complexity-residualized minus original",
        "boundary_definition": (
            "largest matched source N with a strictly positive full-precision CP margin"
        ),
        "shared_symmetric_axis_limits": {
            "delta_shortcut_ceiling": [-ceiling_limit, ceiling_limit],
            "delta_normalized_margin": [-margin_limit, margin_limit],
        },
        "domains": reports,
    }
    report_path = args.output_dir / "fig_2_sensitivity_alignment.json"
    report_path.write_text(json.dumps(audit, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote {report_path}")
    for spec, report in zip(DOMAIN_SPECS, reports):
        print(
            f"{spec.domain}: matched source={report['matched_source_rows']}, "
            f"plotted={report['plotted_rows']}, "
            f"unmatched original={len(report['unmatched_original_rows'])}, "
            f"unmatched residualized={len(report['unmatched_residualized_rows'])}"
        )
        for model, model_report in report["models"].items():
            original = model_report["positive_cp_boundary_original"]
            residualized = model_report["positive_cp_boundary_residualized"]
            if original != residualized:
                print(f"  CP N*: {model}: {original} -> {residualized}")
        print(
            "  missing unchanged fields: "
            f"{len(report['missing_unchanged_fields'])}"
        )
    print(f"Shared ceiling delta limits: +/-{ceiling_limit:.3f}")
    print(f"Shared margin delta limits: +/-{margin_limit:.3f}")


if __name__ == "__main__":
    main()
